export const metadata = {
  title: "Home Page - Nextflix",
  description: "Generated by create next app",
};
import HomeContainer from "@/components/home";

export default function Home() {
  return <HomeContainer />;
}
